spring:

  cloud:
    zookeeper:
      connect-string: localhost:2181
      config:
        enabled: true
        root: configuration
        defaultContext: apps
      discovery:
        enabled: true
      dependency:
        enabled: true
      dependencies:
        eagents:
          path: eagents
          version: v1
          required: false

  config:
    import: "optional:zookeeper:"

server:
  port: 8083
