spring:
  application:
    name: eagent

  cloud:
    zookeeper:
      connect-string: localhost:2181
      config:
        enabled: true
        root: configuration
        defaultContext: apps
      discovery:
        enabled: true
      dependency:
        enabled: true

  config:
    import: "optional:zookeeper:"

#  host: localhost
#  port: 2181
server:
  port: 8081
